- id: doi:10.1094/MPMI-12-24-0159-FI
  type: paper
  date: 2025-04-10
  image: https://apsjournals.apsnet.org/cms/10.1094/MPMI-12-24-0159-FI/asset/images/large/mpmi-12-24-0159-fif2-1745830530167.jpeg
  tags:
    - barley
    - collaboration

- id: doi:10.3390/agronomy12040838
  type: paper
  image: https://www.mdpi.com/agronomy/agronomy-12-00838/article_deploy/html/images/agronomy-12-00838-g001.png

